/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class pembayaran extends javax.swing.JFrame {
    String pesananLainnya;
    int hargane;
    /**
     * Creates new form pembayaran
     */
    DefaultTableModel model;
    public pembayaran() {
        try {
            initComponents();
            String[] judul={"id_penyewa","tanggal_pegembalian","lama_sewa","biayaperjam","pesanan_lainnya","total_bayar"};
            model =new DefaultTableModel(judul,0);
            pengembalian.setModel(model);
            tampildata();
        } catch (SQLException ex) {
            Logger.getLogger(pembayaran.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        id_penyewa = new javax.swing.JTextField();
        tanggal_pengembalian = new javax.swing.JTextField();
        lama_sewa = new javax.swing.JTextField();
        total_bayar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pengembalian = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        biayaperjam = new javax.swing.JTextField();
        menu_makanandanminum = new javax.swing.JComboBox<>();
        regane = new javax.swing.JTextField();
        lain_lain = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 255, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("ID PENYEWA ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 150, 40));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setText("TANGGAL PENGEMBALIAN");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 250, 40));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setText("LAMA SEWA");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, 40));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setText("TOTAL BAYAR ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 140, 40));
        jPanel2.add(id_penyewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 200, 40));
        jPanel2.add(tanggal_pengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 200, 40));

        lama_sewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lama_sewaActionPerformed(evt);
            }
        });
        jPanel2.add(lama_sewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 200, 40));
        jPanel2.add(total_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 200, 40));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setText("WONOKARTO PLAYSTATION");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 350, 50));

        jButton1.setText("TAMBAH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));

        jButton2.setText("EDIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, -1, -1));

        jButton3.setText("HAPUS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, -1, -1));

        jButton4.setText("REFRESH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, -1));

        jButton5.setText("KULUAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, -1, -1));

        pengembalian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        pengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pengembalianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(pengembalian);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 550, 90));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel6.setText("biaya per jam ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 30));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel7.setText("PESANAN LAINNYA ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));
        jPanel2.add(biayaperjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 200, -1));

        menu_makanandanminum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kopi", "roti", "pop mie", "kacang", "aqua" }));
        menu_makanandanminum.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                menu_makanandanminumComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                menu_makanandanminumComponentRemoved(evt);
            }
        });
        menu_makanandanminum.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                menu_makanandanminumItemStateChanged(evt);
            }
        });
        menu_makanandanminum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_makanandanminumActionPerformed(evt);
            }
        });
        jPanel2.add(menu_makanandanminum, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, 20));

        regane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reganeActionPerformed(evt);
            }
        });
        jPanel2.add(regane, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 80, -1));

        lain_lain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lain_lainActionPerformed(evt);
            }
        });
        lain_lain.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lain_lainKeyReleased(evt);
            }
        });
        jPanel2.add(lain_lain, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 80, -1));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel8.setText("jumlah pesanan lainnya ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 618, 452);

        setBounds(0, 0, 623, 490);
    }// </editor-fold>//GEN-END:initComponents

    private void lama_sewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lama_sewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lama_sewaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
      new tabel_menu().setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/rentalps","root","");
            cn.createStatement().executeUpdate("insert into pembayaran values"+"('"+id_penyewa.getText()+"','"+tanggal_pengembalian.getText()+"','"+lama_sewa.getText()+"','"+biayaperjam.getText()+"','"+regane.getText()+"','"+total_bayar.getText()+"')");
            tampildata();
           // reset();
        } catch (SQLException ex) {
            //Logger.getLogger(kamera.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengembalianMouseClicked
        // TODO add your handling code here:
         int i=pengembalian.getSelectedRow();
        
        if(i>-1){
            id_penyewa.setText(model.getValueAt(i,0).toString());
            tanggal_pengembalian.setText(model.getValueAt(i,1).toString());
            lama_sewa.setText(model.getValueAt(i,2).toString());
            biayaperjam.setText(model.getValueAt(i,3).toString());
            regane.setText(model.getValueAt(i,4).toString());
            total_bayar.setText(model.getValueAt(i,5).toString());
        }
    }//GEN-LAST:event_pengembalianMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/rentalps","root","");
            cn.createStatement().executeUpdate("update pembayaran set tgl_pengembalian='"+tanggal_pengembalian.getText()+"', lama_sewa='"+lama_sewa.getText()+"',biayaperjam='"+biayaperjam.getText()+"',regane='"+regane.getText()+"', total_bayar='"+total_bayar.getText()+"' where id_penyewa='"+id_penyewa.getText()+"'");
            tampildata();   
          //  reset();
        } catch (SQLException ex) {
               //Logger.getLogger(kamera.class.getName()).log(Level.SEVERE, null, ex);
               JOptionPane.showMessageDialog(null,ex); 
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/rentalps","root","");
            cn.createStatement().executeUpdate("delete from pembayaran where id_penyewa='"+id_penyewa.getText()+"'");
            tampildata();
            //reset();
        } catch (SQLException ex) {
            //Logger.getLogger(rentalps.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex); 
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        reset();
    }
    public void loadtambahan(){
        pesananLainnya = ""+menu_makanandanminum.getSelectedItem();
        switch(pesananLainnya){
            case "kopi":
                hargane = 5000;
            break;
            case "roti":
                hargane = 10000;
            break;
            case "pop mie":
                hargane = 8000;
            break;
            case "kacang":
                hargane = 6000;
            break;
            case "aqua":
                hargane = 4000;
            break;
            
        }
    regane.setText(""+hargane);
    }
    private void reset (){
        id_penyewa.setText("");
        tanggal_pengembalian.setText("");
        lama_sewa.setText("");
        biayaperjam.setText("");
        regane.setText("");
        total_bayar.setText(""); 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void menu_makanandanminumItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_menu_makanandanminumItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menu_makanandanminumItemStateChanged

    private void menu_makanandanminumComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_menu_makanandanminumComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_makanandanminumComponentAdded

    private void menu_makanandanminumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_makanandanminumActionPerformed
        loadtambahan();
       // int lama,biaya,tambahan,total;
//        lama = Integer.parseInt(lama_sewa.getText());
  //      biaya = Integer.parseInt(biayaperjam.getText());
       // tambahan = Integer.parseInt(regane.getText());
        //total = lama * biaya + tambahan;
        //total_bayar.setText(Integer.toString(total));
        
    }//GEN-LAST:event_menu_makanandanminumActionPerformed

    private void reganeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reganeActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_reganeActionPerformed

    private void lain_lainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lain_lainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lain_lainActionPerformed

    private void menu_makanandanminumComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_menu_makanandanminumComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_makanandanminumComponentRemoved

    private void lain_lainKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lain_lainKeyReleased
        // TODO add your handling code here:
        loadtambahan();
        if(lain_lain.getText() != null){
        int lama,biaya,tambahan,lain;
                lama = Integer.parseInt(lama_sewa.getText());
                biaya = Integer.parseInt(biayaperjam.getText());
                tambahan = Integer.parseInt(regane.getText());
                lain = Integer.parseInt(lain_lain.getText());
                int total = lama * biaya + tambahan * lain;
        total_bayar.setText(Integer.toString(total));
        }
    }//GEN-LAST:event_lain_lainKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField biayaperjam;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField id_penyewa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lain_lain;
    private javax.swing.JTextField lama_sewa;
    private javax.swing.JComboBox<String> menu_makanandanminum;
    private javax.swing.JTable pengembalian;
    private javax.swing.JTextField regane;
    private javax.swing.JTextField tanggal_pengembalian;
    private javax.swing.JTextField total_bayar;
    // End of variables declaration//GEN-END:variables

    private void tampildata() throws SQLException {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    model= new DefaultTableModel();
       pengembalian.setModel(model);
       model.addColumn("id_penyewa");
       model.addColumn("tanggal_pengembalian");
       model.addColumn("lama_sewa");
       model.addColumn("biayaperjam");
       model.addColumn("regane");
       model.addColumn("total_bayar");
       
//try{
       Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/rentalps","root","");
      ResultSet res=cn.createStatement().executeQuery("select * FROM pembayaran");
      while(res.next()){
          Object[]obj= new Object[6];
          obj[0]=res.getString("id_penyewa");
          obj[1]=res.getString("tgl_pengembalian");
          obj[2]=res.getString("lama_sewa");
          obj[3]=res.getString("biayaperjam");
          obj[4]=res.getString("regane");
          obj[5]=res.getString("total_bayar");
          
          model.addRow(obj);
      }
       }
    }
