/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class penyewa extends javax.swing.JFrame {

    /**
     * Creates new form penyewa
     */
    DefaultTableModel model;
    public penyewa() {
        initComponents();    
    String[] judul={"id_penyewa","nama_penyewa","alamat","no_telpon","tgl_sewa"};
        model =new DefaultTableModel(judul,0);
        sewa.setModel(model);
        tampildata();

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nama_penyewa = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        no_telpon = new javax.swing.JTextField();
        tanggal_sewa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        sewa = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        id_penyewa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("nama penyewa");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, -1));

        jLabel2.setText("alamat");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 70, 20));

        jLabel3.setText("no telpon ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 70, 30));

        jLabel4.setText("tanggal sewa");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 100, 30));

        nama_penyewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_penyewaActionPerformed(evt);
            }
        });
        jPanel1.add(nama_penyewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 90, -1));
        jPanel1.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 90, -1));
        jPanel1.add(no_telpon, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 90, -1));
        jPanel1.add(tanggal_sewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 90, -1));

        jButton1.setText("tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jButton2.setText("hapus ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        jButton3.setText("edit ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        jButton4.setText("keluar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        sewa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "title 5"
            }
        ));
        sewa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sewaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(sewa);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 460, 100));

        jButton5.setText("refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        jLabel5.setText("id_pelanngan ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        jPanel1.add(id_penyewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 90, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 18)); // NOI18N
        jLabel6.setText("WONOKARTO PLAYSTATION");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 320, 30));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 510, 420);

        setSize(new java.awt.Dimension(522, 459));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nama_penyewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_penyewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_penyewaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
 new tabel_menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/rentalps","root","");
            cn.createStatement().executeUpdate("insert into penyewa values"+"('"+id_penyewa.getText()+"','"+nama_penyewa.getText()+"','"+alamat.getText()+"','"+no_telpon.getText()+"','"+tanggal_sewa.getText()+"')");
            tampildata();
            reset();
        } catch (SQLException ex) {
            //Logger.getLogger(kamera.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sewaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sewaMouseClicked
        // TODO add your handling code here:
         int i=sewa.getSelectedRow();
        
        if(i>-1){
            id_penyewa.setText(model.getValueAt(i,0).toString());
            nama_penyewa.setText(model.getValueAt(i,1).toString());
            alamat.setText(model.getValueAt(i,2).toString());
            no_telpon.setText(model.getValueAt(i,3).toString());
            tanggal_sewa.setText(model.getValueAt(i,4).toString());
        }

    }//GEN-LAST:event_sewaMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       // TODO add your handling code here:
       try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/rentalps","root","");
            cn.createStatement().executeUpdate("delete from penyewa where id_penyewa='"+id_penyewa.getText()+"'");
            tampildata();
            reset();
        } catch (SQLException ex) {
            //Logger.getLogger(rentalps.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex); 
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/rentalps","root","");
            cn.createStatement().executeUpdate("update penyewa set nama_penyewa='"+nama_penyewa.getText()+"', alamat='"+alamat.getText()+"', no_telpon='"+no_telpon.getText()+"', tgl_sewa='"+tanggal_sewa.getText()+"' where id_penyewa='"+id_penyewa.getText()+"'");
            tampildata();   
            reset();
        } catch (SQLException ex) {
               //Logger.getLogger(kamera.class.getName()).log(Level.SEVERE, null, ex);
               JOptionPane.showMessageDialog(null,ex); 
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
reset();
    }
    private void reset (){
        id_penyewa.setText("");
        nama_penyewa.setText("");
        alamat.setText("");
        no_telpon.setText("");
        tanggal_sewa.setText(""); 
                
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new penyewa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField id_penyewa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nama_penyewa;
    private javax.swing.JTextField no_telpon;
    private javax.swing.JTable sewa;
    private javax.swing.JTextField tanggal_sewa;
    // End of variables declaration//GEN-END:variables

    private void tampildata() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
   int row = sewa.getRowCount();
           for (int a= 0; a<row;a++){
               model.removeRow(0);
           }
           try {
               Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/rentalps","root","");
               ResultSet rs=cn.createStatement().executeQuery ("select * from penyewa");
               while(rs.next()) {
                   String data []={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)};
                   model.addRow(data);
               }
           
               } catch (SQLException ex){
                   Logger.getLogger(penyewa.class.getName()).log(Level.SEVERE,null,ex);
           }
    }
}
